name: Nuclei Redirect Scan

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Nuclei
        run: |
          VERSION=$(curl -s https://api.github.com/repos/projectdiscovery/nuclei/releases/latest | jq -r .tag_name | sed 's/v//')
          wget "https://github.com/projectdiscovery/nuclei/releases/download/v${VERSION}/nuclei_${VERSION}_linux_amd64.zip"
          unzip nuclei_*.zip
          sudo mv nuclei /usr/local/bin/
          nuclei -version


      - name: Update Templates
        run: nuclei -update-templates

      - name: Run Redirect Scan (LOW RATE)
        run: |
          nuclei -l targets.txt \
          -tags redirect \
          -o redirect_results.txt

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: redirect-results
          path: redirect_results.txt
